services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432

    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped

  db:
    image: postgres:16
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    depends_on:
      - db
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  pgdata:
